#!/bin/bash
#
# create update package
if [ -d upgrade ] ; then rm -rf upgrade ; fi 
if [ -f upgrade*.tar.xz ] ; then rm -rf upgrade*.tar.xz ; fi 
mkdir tmp upgrade
cp -a tar-install/lib tmp/
fakeroot chown -R root.root tmp/
fakeroot /usr/bin/mksquashfs tmp/  upgrade/kmod.squash -comp xz
rm -rf tmp
gitrev=`/usr/bin/git rev-parse --short HEAD`
dtbfile=`grep CONFIG_UPGRADE_DTBFILE .config | awk -F '"' '{print $2}'`
if [ -z "$dtbfile" ]; then 
    echo "upgrade dtb file is not set in .config, aborting"
    rm -rf upgrade
    exit 1;
fi
cp -a arch/arm/boot/zImage upgrade/
cp -a arch/arm/boot/dts/$dtbfile upgrade/
fakeroot chown -R root.root upgrade/
fakeroot md5sum upgrade/* > upgrade/MD5SUM
tar -cJf upgrade-$gitrev.tar.xz upgrade

echo "update package created : upgrade-$gitrev.tar.xz"
